[[redirects]]
  from = “/api/*”
  to = “https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.1702401&lng=72.83106070000001&is-seo-widgets-enabled=true&page_type=DESKTOP_WEB_LISTING"
  status = 200
[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200